---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frigate
  annotations:
    'backstage.io/kubernetes-id': frigate
    'backstage.io/kubernetes-namespace': frigate
spec:
  type: service
  lifecycle: experimental
  owner: guests
