apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  labels:
    app: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      volumes:
        - name: frigate-config
          configMap:
            name: frigate-config
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:0.12.1-tensorrt
          envFrom:
            - secretRef:
                name: frigate-secret
          volumeMounts:
            - mountPath: /config
              name: frigate-config
          ports:
            - containerPort: 5000
          resources:
            limits:
              gpu.intel.com/i915: 1
