apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  replicas: 1
  selector:
  template:
    metadata:
      annotations:
        fluentbit.io/parser: nginx
    spec:
      volumes:
        - name: frigate-config-file
          configMap:
            name: frigate-config
        - name: frigate-media
          persistentVolumeClaim:
            claimName: frigate-media-pvc
        - name: frigate-config
          persistentVolumeClaim:
            claimName: frigate-config-pvc
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: frigate-secret
          volumeMounts:
            - mountPath: /config
              name: frigate-config
            - mountPath: /config/config.yml
              name: frigate-config-file
              subPath: config.yml
            - mountPath: /media/frigate
              name: frigate-media
          ports:
            - containerPort: 5000
          resources:
            limits:
              gpu.intel.com/i915: 1
