---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
namespace: frigate
configMapGenerator:
  - name: frigate-config
    namespace: frigate
    files:
      - config.yml
secretGenerator:
  - name: frigate-secret
    namespace: frigate
    envs:
      - .env.secret
    type: Opaque
