---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frigate-media-pvc
spec:
  storageClassName: frigate-media-storageclass
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi

